import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting started',
      items: ['installation', 'quick-start'],
    },
    {
      type: 'doc',
      id: 'options',
    },
    {
      type: 'doc',
      id: 'references',
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides',
        },
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      items: [
        {
          type: 'autogenerated',
          dirName: 'examples',
        },
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: [
        {
          type: 'autogenerated',
          dirName: 'advanced',
        },
      ],
    },
    {
      type: 'doc',
      id: 'performance',
    },
    {
      type: 'doc',
      id: 'projects',
    },
    {
      type: 'doc',
      id: 'contributing',
    },
    {
      type: 'category',
      label: 'Release notes',
      items: ['release-notes/v2.2.0', 'release-notes/v2.1.0', 'release-notes/v2.0.0'],
    },
  ],
};

export default sidebars;
